# Generated by Django 4.1.7 on 2023-05-16 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Saddress',
            field=models.TextField(max_length=200),
        ),
        migrations.AddConstraint(
            model_name='student',
            constraint=models.CheckConstraint(check=models.Q(('Sage__gte', 3)), name='Sage_gt3'),
        ),
    ]
