# Generated by Django 4.1.7 on 2023-05-16 16:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_student_saddress_student_sage_gt3'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='student',
            name='Sage_gt3',
        ),
        migrations.AlterField(
            model_name='student',
            name='Sage',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(3)]),
        ),
        migrations.AlterField(
            model_name='student',
            name='Sname',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator('[A-Z][a-zA-z]*')]),
        ),
    ]
