# Generated by Django 4.1.7 on 2023-05-16 17:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_student_sage_gt3_alter_student_sage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Sname',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator('[A-Z]*[a-zA-z]')]),
        ),
    ]
